name: Deploy to Railway

on:
  push:
    branches: [ "main" ]

concurrency:
  group: railway-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Deploy with Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
        run: |
          npx -y @railway/cli login --token "$RAILWAY_TOKEN"
          npx -y @railway/cli link --project "$RAILWAY_PROJECT_ID" --service "$RAILWAY_SERVICE_ID"
          npx -y @railway/cli up --yes
