name: Deploy to Railway

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: railway-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Debug Railway token and project access
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          set -euo pipefail
          npx -y @railway/cli login --token "$RAILWAY_TOKEN"
          npx -y @railway/cli whoami || true
          npx -y @railway/cli project list || true

      - name: Link Railway project/service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
          RAILWAY_ENVIRONMENT_ID: ${{ secrets.RAILWAY_ENVIRONMENT_ID }}
        run: |
          set -euo pipefail
          npx -y @railway/cli login --token "$RAILWAY_TOKEN"
          EXTRA_ENV=""
          if [ -n "${RAILWAY_ENVIRONMENT_ID:-}" ]; then EXTRA_ENV="--environment ${RAILWAY_ENVIRONMENT_ID}"; fi
          npx -y @railway/cli link --project "$RAILWAY_PROJECT_ID" --service "$RAILWAY_SERVICE_ID" $EXTRA_ENV

      - name: Deploy (railway up)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          set -euo pipefail
          npx -y @railway/cli login --token "$RAILWAY_TOKEN"
          npx -y @railway/cli up --yes
